---
title: "Linear mixed effect model"
author: "Stefano Coretta"
date: "22/02/2017"
output: pdf_document
---

```{r setup, include=FALSE}
library(knitr)
opts_knit$set(root.dir=normalizePath('../'))
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(tidyr)
library(lme4)
library(effects)
library(afex)
library(ggplot2)
theme_set(theme_bw())
library(car)
```

```{r data}
words <- read_csv("task/task-src/words.csv")

icelandic <- read_csv("results/results.csv", na = "--undefined--") %>%
    right_join(y = words) %>%
    mutate(syllables = factor(syllables, c("mono","di"))) %>%
    mutate(vowel = factor(vowel, c("i", "ɪ", "ʏ", "e", "œ", "a", "o", "ei", "ai", "ou"))) %>%
    mutate_if(is.character, as.factor) 
```

# Duration of vowels vs. aspiration

```{r lmer}
model1 <- lmer(vowel.dur ~ aspiration + vor + (1|speaker) + (1|word),
              data = icelandic
              )

summary(model1)
plot(allEffects(model1))
```

```{r mixed-all}
mixed(vowel.dur ~ aspiration + place + manner + syllables + vowel +
                  cons1 + vor + (1|speaker) + (1|word),
              data = icelandic)
```


```{r lmer2}
model2 <- lmer(voicing.dur ~ aspiration + place + manner + syllables + vowel +
                  cons1 + vor + (1|speaker) + (1|word),
              data = icelandic
              )

summary(model2)
plot(allEffects(model2))
```

# Stops

```{r stops}
stops <- filter(icelandic, manner == "stop")
```

```{r stops-word-dur}
model.stops.words <- lmer(word.dur ~ aspiration +
                              syllables +
                              (1 + aspiration|speaker) +
                              (1|word),
                     data = stops,
                     REML = FALSE
                     )

summary(model.stops.words)
plot(allEffects(model.stops.words))

mixed(word.dur ~ aspiration +
          syllables +
          (1 + aspiration|speaker) +
          (1|word),
      data = stops,
      REML = FALSE
      )
```

```{r stops-vor}
model.stops.vor <-  lmer(vor ~ aspiration *
                             syllables +
                             (1 + aspiration|speaker) +
                             (1|word),
                     data = stops,
                     REML = FALSE
                     )

summary(model.stops.vor)
plot(allEffects(model.stops.vor))

mixed(
    vor ~ aspiration *
    syllables +
    (1 + aspiration | speaker) +
    (1 | word),
    data = stops,
    REML = FALSE
    )
```

```{r lmer-vor-closure}
model.vor.closure <- lmer(vor ~ closure.dur +
                              syllables +
                              (1|speaker) +
                              (1|word),
                          data = stops,
                          REML = FALSE
                              )

summary(model.vor.closure)
plot(allEffects(model.vor.closure))
```


```{r lmer-geminate}
model.geminate <-  lmer(vowel.dur ~ closure.dur*aspiration*syllables +
                            word.dur +
                            (1|speaker) +
                            (1|word),
                        data = stops, REML = FALSE
                        )

summary(model.geminate)
plot(allEffects(model.geminate))

mixed(vowel.dur ~ closure.dur*aspiration*syllables +
                            word.dur +
                            (1|speaker) +
                            (1|word),
                        data = stops, REML = FALSE
      )
```

```{r lmer-geminate-duration}
model.geminate.duration <-  lmer(cluster.dur ~ aspiration + vor +
                         (1|speaker) + (1|word),
                     data = stops, REML = FALSE
                     )

summary(model.geminate.duration)
plot(allEffects(model.geminate.duration))
```


```{r lmer-stops}
model.stops <-  lmer(vowel.dur ~ aspiration + vor +
                         (1 + aspiration|speaker) + (1|word),
                     data = stops, REML = FALSE
                     )

summary(model.stops)
plot(allEffects(model.stops))
```

```{r mixed-stops}
mixed(vowel.dur ~ aspiration + vor + (1 + aspiration|speaker) + (1|word),
              data = stops)
```

```{r likelihood-stops}
model.stops.null <- lmer(vowel.dur + vor ~ (1|speaker) + (1|word),
              data = stops, REML = FALSE)

anova(model.stops.null, model.stops)
```

# Nasals

```{r nasals}
icelandic.nasals <- filter(icelandic, manner == "nasal") %>%
    droplevels()
```

```{r lmer-nasals-vor}
model.nasals.vor <-  lmer(vor ~ aspiration + syllables +
                              (1 + aspiration|speaker) + (1|word),
                     data = icelandic.nasals, REML = FALSE
                     )

summary(model.nasals.vor)
plot(allEffects(model.nasals.vor))
```

```{r lmer-nasals-closure}
model.nasals.closure <-  lmer(closure.dur ~ aspiration + syllables +
                              (1 + aspiration|speaker) + (1|word),
                     data = icelandic.nasals, REML = FALSE
                     )

summary(model.nasals.closure)
plot(allEffects(model.nasals.closure))
```

```{r plot-nasals-vowels}
ggplot(icelandic.nasals, aes(vowel.dur, dur_mann, colour = syllables)) +
    facet_grid(. ~ speaker) +
    geom_point()
```

```{r lmer-nasals-vowels}
model.vowels.nasals <- lmer(vowel.dur ~ dur_mann + vor + syllables +
                          (1|speaker) +
                          (1|word),
                     data = icelandic.nasals, REML = FALSE
                     )

summary(model.vowels.nasals)

plot(allEffects(model.vowels.nasals))
```

```{r lmer-nasals}
model.nasals <-  lmer(vowel.dur ~ aspiration + vor + syllables +
                          (1 + aspiration|speaker) +
                          (1|word),
                     data = icelandic.nasals, REML = FALSE
                     )

summary(model.nasals)
plot(allEffects(model.nasals))
```

# Voicing duration and spreading duration

```{r spreading.dur}
icelandic.aspirated.stops <- filter(icelandic, manner == "stop",
                                    aspiration == "yes"
                                    )
```

```{r lmer-spreading.dur}
model.aspirated <- lmer(voicing.dur ~ spreading.dur + syllables + vor + vowel +
                            (1|speaker) + (1|word),
                        data = icelandic.aspirated.stops
                        )

summary(model.aspirated)
plot(allEffects(model.aspirated))
```

```{r mixed-spreading.dur}
mixed(voicing.dur ~ spreading.dur + syllables + vor + vowel +
                            (1|speaker) + (1|word),
                        data = icelandic.aspirated.stops
                        )
```

# Proportions

```{r proportions}
stops.proportions1 <- icelandic %>%
    filter(manner == "stop", aspiration == "yes") %>%
    group_by(aspiration) %>%
    summarise(total = mean(vowel.dur, na.rm = TRUE) + mean(spreading.dur, na.rm = TRUE) +
                  mean(closure.dur, na.rm = TRUE),
              vowel = mean(vowel.dur, na.rm = TRUE) / total,
              spreading = mean(spreading.dur, na.rm = TRUE) / total,
              closure = mean(closure.dur, na.rm = TRUE) / total
              ) %>%
    gather(segment, duration, vowel:closure) %>%
    mutate(segment = factor(segment, c("closure","spreading","vowel")))

stops.proportions2 <- icelandic %>%
    filter(manner == "stop", aspiration == "no") %>%
    group_by(aspiration) %>%
    summarise(total = mean(vowel.dur, na.rm = TRUE) +
                  mean(closure.dur, na.rm = TRUE),
              vowel = mean(vowel.dur, na.rm = TRUE) / total,
              closure = mean(closure.dur, na.rm = TRUE) / total
              ) %>%
    gather(segment, duration, vowel:closure) %>%
    mutate(segment = factor(segment, c("closure","vowel")))

stops.proportions <- rbind(stops.proportions1, stops.proportions2)

sonorants.proportions <- icelandic %>%
    filter(manner %in% c("lateral", "nasal", "rhotic")) %>%
    group_by(manner, aspiration) %>%
    summarise(total = mean(vowel.dur) + mean(sonorant.dur) +
                  mean(closure.dur),
              vowel = mean(vowel.dur) / total,
              c1 = mean(sonorant.dur) / total,
              c2 = mean(closure.dur) / total
              ) %>%
    gather(segment, duration, vowel:c2) %>%
    mutate(segment = factor(segment, c("c2","c1","vowel"))) %>%
    unite(type, manner, aspiration)
```

```{r}
ggplot(sonorants.proportions, aes(type, duration, fill = segment)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    guides(fill = guide_legend(reverse = TRUE))

ggplot(stops.proportions, aes(aspiration, duration, fill = segment)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    guides(fill = guide_legend(reverse = TRUE))
```
